services:
    - type: web
      name: symfony-web
      env: docker
      repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
      branch: main
      autoDeploy: true
      plan: free
      envVars:
          - key: APP_ENV
            value: prod
          - key: DATABASE_URL
            fromDatabase:
                name: symfony-db
                property: connectionString

databases:
    - name: symfony-db
      databaseName: symfony
      user: symf_user
